name: 🧩 Validate, Build and Release

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  validate:
    name: Validate Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 🧠 Hassfest Validation
        uses: home-assistant/actions/hassfest@master

      - name: 🧩 HACS Validation
        uses: hacs/action@main
        with:
          category: integration

  build_release:
    name: Build ZIP and Create Release
    runs-on: ubuntu-latest
    needs: validate
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bleak bleak-retry-connector

      - name: Bump version in manifest.json
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "Updating version to $VERSION"
          sed -i "s/\"version\": \".*\"/\"version\": \"${VERSION#v}\"/" custom_components/elkbledom_fastlink/manifest.json

      - name: Commit and push manifest bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump manifest.json to v${{ steps.version.outputs.new_version }}"
          file_pattern: custom_components/elkbledom_fastlink/manifest.json
          branch: main
          tagging_message: "v${{ steps.version.outputs.new_version }}"
          push_options: --force

      - name: Create ZIP archive
        run: |
          mkdir -p release
          cd custom_components
          zip -r ../release/elkbledom-fastlink.zip elkbledom_fastlink -x "*.pyc" "__pycache__/*"
          cd ..

      - name: Upload ZIP as release asset
        uses: softprops/action-gh-release@v2
        with:
          files: release/elkbledom_fastlink.zip
          name: "ELK-BLEDOM FastLink ${{ github.ref_name }}"
          body: |
            🚀 **ELK-BLEDOM FastLink** ${{ github.ref_name }}
            - Мгновенное подключение по Bluetooth
            - Стабильное соединение без засыпаний
            - Поддержка эффектов и RGB5050
            - Оптимизированная яркость и цветопередача
          draft: false
          prerelease: false
