name: 🚀 Build ZIP and Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bleak bleak-retry-connector bluepy

      - name: Bump version in manifest.json
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "Updating version to $VERSION"
          sed -i "s/\"version\": \".*\"/\"version\": \"${VERSION#v}\"/" custom_components/elkbledom/manifest.json

      - name: Commit and push manifest bump
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump manifest.json to ${{ github.ref_name }}"
          file_pattern: custom_components/elkbledom/manifest.json
          branch: main
          tagging_message: "${{ github.ref_name }}"

      - name: Create ZIP archive
        run: |
          mkdir -p release
          cd custom_components
          zip -r ../release/elkbledom-fastlink.zip elkbledom -x "*.pyc" "__pycache__/*"
          cd ..

      - name: Upload ZIP as release asset
        uses: softprops/action-gh-release@v2
        with:
          files: release/elkbledom-fastlink.zip
          name: "ELK-BLEDOM FastLink ${{ github.ref_name }}"
          body: |
            🚀 **ELK-BLEDOM FastLink** ${{ github.ref_name }}
            - Быстрое Bluetooth-соединение без отвалов
            - Поддержка эффектов и RGB 5050
            - Мгновенное управление яркостью и цветом
          draft: false
          prerelease: false
