name: HACS Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  hacs:
    name: "HACS Validation - ELK-BLEDOM FastLink"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: "integration"
          repository: "Satimaro/elkbledom-fastlink"
          ignore: "topics"
          comment: false

      - name: Success message
        if: success()
        run: echo "✅ HACS validation passed for ELK-BLEDOM FastLink"

      - name: Failure message
        if: failure()
        run: echo "❌ HACS validation failed. Check the logs for details."
